### ISSUE TITLE
bug(md-editor) Pasting in code within a fenced code block, creates 2nd inner code block

### ISSUE THREAD

**Issue by KyleMit** [StackExchange/Stacks-Editor#215] opened 2022-08-18 18:33 UTC
**Describe the bug**
In the markdown editor, when pasting code into a pre-existing fenced code block, a second code block is created inside.

**To Reproduce**
1. Open md editor
2. Create fenced code block <code>```</code>
3. Paste anything detected as code into block - ex: copy the text below:

    ```
    var x = 1
    ```

**Expected behavior**
Only the single (existing) fenced region is used

**Screenshots**
![paste-code-into-code](https://user-images.githubusercontent.com/4307307/185468587-5c915b1e-0681-461d-8a3c-f74458694e78.gif)

This will also render incorrectly if saved without manually fixing:

![image](https://user-images.githubusercontent.com/4307307/185467959-466adfd2-929c-4560-b162-55e0d1b8e067.png)

**Desktop**
 - OS: Windows
 - Browser: Chrome
 - Version: v104

**Comment by b-kelly** [comment] 2022-08-18 18:45
Currently, this is working "by design". Unlike rich-text mode, we don't have any easy way to detect what type of "node" you're modifying. Because of this, you're going to see issue like the one you describe. Although I do agree that the current behavior is not ideal, this would take quite a bit of effort to resolve due to a number of factors. Because of this, I'm placing it in the backlog to revisit at a later date.

<details><summary>Notes to self</summary>

How would we handle the following edge cases?

```md
indented code blocks (pretend the dots are spaces)
····paste here
```

~~~md
unterminated code blocks (yes, this is legal: https://spec.commonmark.org/0.30/#example-126)
```
paste here
~~~

</details>

**Comment by yellis** [comment] 2022-10-27 06:37
potentially related to #230

**Comment by gparyani** [comment] 2022-11-11 20:12
Relevant Meta.SE report: https://meta.stackexchange.com/q/383727/377214

**Comment by giamir** [comment] 2022-12-12 17:13
Fixed by https://github.com/StackExchange/Stacks-Editor/releases/tag/v0.8.3

**Closed by giamir** 2022-12-12 17:13 UTC
Labels: enhancement, mode - markdown
